version: '3.8'

services:
  db:
    image: postgres:16
    container_name: knox-id-store
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
